### PR TITLE
Fixing Java Hello World Test

### PR DESCRIPTION
**Pull request by nareshbhandari**
- fix(java-test): Replacing deprecated SpringApplicationConfiguration with SpringBootTest. Tests were failing due to deprecated classes.
- chore(upgrade): Upgrading Spring Boot framework version from 2.1.2 to 2.14

### CODE REVIEW

**Comment by nareshbhandari** [comment]
I signed it!

**Comment by redborian** [comment]
@simonz130 Do you know who can review this PR?

**Comment by iantalarico** [comment]
@saturnism @etanshaul Maybe one of you can TAL?

**Comment by patflynn** [comment]
@simonz130 ping. Who is owning maintenance of these samples?  This seems to have sat broken for a very long time.  

Seems like these projects need CI. Is there an open issue?

**Pull request merged**
