### PR TITLE
Cloud Run frontend content update

### PR DESCRIPTION
**Pull request by kelsk**
Changes:
* Separate "What's next?" content into 2 sections (see image)
* Remove `PROJECT` metadata (addresses #367) 

image

### CODE REVIEW

**Comment by chairy** [comment]
Looks good!! Some nits:
- I think we are duplicating the links to ask users to sign up for research. We can drop the button.
- "Explore more options with" could be replaced with "Read our documentation" (or something that hints that links will point them to product documentation)
- I think the official name for Cloud Run is "Cloud Run" rather than "Google Cloud Run"? [brand guideline](https://cloud.google.com/guides/style/branding-guidelines)

**Comment by kelsk** [comment]
@chairy good nits! implementing them now.

do you think it makes sense to replace the SIGN UP FOR USER RESEARCH button with something like [CLOUD CODE ON CLOUD SHELL](https://cloud.google.com/shell/docs/editor-overview#cloud_code_integration) ?

**Review by Shabirmean — APPROVED** [review]
Tested all 6 sample apps wth the latest changes and LGTM!

**Pull request merged**
