### PR TITLE
Update skaffold schema to v1beta15

### PR DESCRIPTION
**Pull request by simonz130**
This will mitigate the issue visible in intellij when working with the the templates

### CODE REVIEW

**Comment by simonz130** [comment]
Solves #157

**Comment by ivanporty** [comment]
@simonz130 this should be good to go, but CI fails - I think some problem with Python samples after the latest upgrades?

**Comment by ivanporty** [comment]
But anyway, regardless of the CI results, we need to get this in ASAP, currently essentially quick start / samples flow is completely broken for CC IJ.

**Comment by simonz130** [comment]
Merging to unblock IntelliJ and will open a separate issue on CI failure.

**Pull request merged**
