### PR TITLE
Fix debug port in Java's Dockerfile

### PR DESCRIPTION
**Pull request by quoctruong**
Change the ports in the Dockerfile to match the ones in "launch.json" file.

### CODE REVIEW

**Comment by iantalarico** [comment]
Why are we switching these? Isn't 5005 the standard port?

@etanshaul @ivanporty

**Comment by etanshaul** [comment]
They should be 5005. This is the standard. I just made this change. Sorry - I should have checked to see how this affects VS Code.

**Comment by etanshaul** [comment]
https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/50

**Comment by etanshaul** [comment]
Fwiw I don’t think it really matters, as long as it’s not in the privileged port range. But 5005 (not 50005) is what I normally see as the default.

**Comment by iantalarico** [comment]
Looks like we are using 50005 in our defaults, we should probably change this given that 5005 is the default.  We may want to revert this and change it back as a fast follow of a Cloud Code VS Code release?

@quoctruong How does this affect our bits if we leave it as 5005?

**Comment by etanshaul** [comment]
> We may want to revert this and change it back as a fast follow of a Cloud Code VS Code release?

This is fine. We can remember to update this after the next VS Code release (I assume this is breaking debugging for the Java apps - sorry again..). FWIW, once we all integrate `skaffold debug` we can get rid of this :)

**Comment by quoctruong** [comment]
@iantalarico @etanshaul PTAL. I changed all the ports to 5005 instead.

**Comment by etanshaul** [comment]
Oh right! the vs code launch configs live here in the samples, not the extension. So we don't have to wait for a release.

**Comment by quoctruong** [comment]
Thanks!

**Pull request merged**
