### PR TITLE
Revert org.springframework.boot:spring-boot-starter-parent from 2.3.0.RELEASE to 2.1.4.RELEASE/2.1.2.RELEASE

### PR DESCRIPTION
**Pull request by matthewmichihara**
Fixes https://github.com/GoogleCloudPlatform/cloud-code-samples/issues/353

### CODE REVIEW

**Comment by etanshaul** [comment]
@simonz130 I wonder a couple things:

- How did samples presubmit not catch this. It appears to be a build failure.
- Can we update the API call to work with the latest spring-boot jar? I'm fine reverting the jar upgrade temporarily to unblock this issue.

**Comment by etanshaul** [comment]
I'm not sure what procedure we want to follow for PR approvers, but since this is high priority I went ahead and approved.

**Comment by simonz130** [comment]
@etanshaul, I'll merge this PR to unblock the users.
Not sure why this wasn't caught by the CI - we need to investigate this. Let's discuss it offline.

**Comment by matthewmichihara** [comment]
confirmed that this fixed our issues, thanks @simonz130

**Pull request merged**
