### PR TITLE
Java: use Alpine base image

### PR DESCRIPTION
**Pull request by ace-n**

### CODE REVIEW

**Comment by gsquared94** [comment]
@ace-n  `maven:3-eclipse-temurin-11-alpine` image is only supported for `linux/amd64` platform. These examples will stop working for GKE ARM node clusters with this change.

```
❯ docker manifest inspect maven:3-eclipse-temurin-11-alpine
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1996,
         "digest": "sha256:9fae05116a9c9a0149f1c7ef19dd547d45214b4edb90877dde4eb665575977f2",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```
```
❯ docker manifest inspect maven:3-jdk-11-slim
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1996,
         "digest": "sha256:d12b61d6ea1938fd3f8b194f06276a2b70b4f1f5b2a87304a7c0c585db64b242",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1996,
         "digest": "sha256:ae33ea891b98a75be0b6ef2e422670dab312bd93d944e63e81fca0650dd4ae56",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
```

**Comment by ace-n** [comment]
I wonder if we could use [this JRE-only image](https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/8-jre-focal/images/sha256-e4965985a370d89aa118c36d6e53301cf5ae084d1b0d1b272179fee7104d5c20?context=explore) instead?

_(If we need the JDK itself, it's probably better to close this PR as **Infeasible**.)_

**Comment by ace-n** [comment]
**Update:** `eclipse-temurin:8-jre-focal` won't work here.

Given the trouble finding a matching image and that this is low-priority, I'm closing this PR.

**Pull request closed without merging**
