### PR TITLE
Workaround for java buildpacks on Windows

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by matthewmichihara** [comment]
Verified that this `mvnw` not found issue we were seeing on Windows.

**Comment by dgageot** [comment]
@matthewmichihara you mean it fixes it?

**Comment by matthewmichihara** [comment]
> @matthewmichihara you mean it fixes it?

accidentally omitted some words, yes it fixes it

**Pull request merged**
