### PR TITLE
fix: nodejs-guestbook buildpacks builder not working

### PR DESCRIPTION
**Pull request by gsquared94**
running `skaffold build -p buildpacks` in the `nodejs/nodejs-guestbook` app from an M1 Mac always results in the following error:
```
...

[builder] npm ERR! A complete log of this run can be found in:
[builder] npm ERR!     /home/cnb/.npm/_logs/2022-07-30T07_44_41_031Z-debug-0.log
[builder] --------------------------------------------------------------------------------
[builder] Sorry your project couldn't be built.
[builder] Our documentation explains ways to configure Buildpacks to better recognise your project:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md
[builder] If you think you've found an issue, please report it:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
[builder] --------------------------------------------------------------------------------
[builder] ERROR: failed to build: exit status 1
```
Setting the nodejs version explicitly according to https://github.com/GoogleCloudPlatform/buildpacks/issues/215 fixes the issue.

### CODE REVIEW

**Comment by ace-n** [comment]
Should we use Node 16 instead, given that it's in [Active LTS](https://nodejs.org/en/about/releases/)?

**Comment by gsquared94** [comment]
> Should we use Node 16 instead, given that it's in [Active LTS](https://nodejs.org/en/about/releases/)?

Done!

**Review by ace-n — APPROVED** [review]

**Pull request merged**
