### PR TITLE
added parent pom for guestbook

### PR DESCRIPTION
**Pull request by daniel-sanche**
As discussed  in https://github.com/GoogleCloudPlatform/cloud-code-samples/issues/24

### CODE REVIEW

**Review by simonz130 — APPROVED** [review]

**Comment by simonz130** [comment]
@etanshaul can you please try the fix that Dan suggested before we merge it?

**Comment by etanshaul** [comment]
taking a look

**Comment by etanshaul** [comment]
```
, stderr: error: error validating "/Users/eshaul/dev/samples/cloud-code-samples/java/java-guestbook/kubernetes-manifests/guestbook-backend.deployment.yaml": error validating data: ValidationError(Deployment.spec.template): unknown field "initContainers" in io.k8s.api.core.v1.PodTemplateSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
are you seeing this?

**Comment by DanSanche** [comment]
Hmm adding the the initContainers field was [proposed here](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/16), but I thought we had decided not to add it. @simonz130?

**Comment by DanSanche** [comment]
actually according to [this commit](https://github.com/GoogleCloudPlatform/cloud-code-samples/commit/0e439c38f70ff35e3b24f59d50d59c5253f24c23) it was added to master by mistake due to a bad merge. I merged the current master back into the PR, so that section should be gone

**Comment by etanshaul** [comment]
ok. it runs now

**Review by etanshaul — APPROVED** [review]

**Pull request merged**
