### PR TITLE
fix: Add note about VS Code UI change

### LINKED ISSUE #1024: vscode README references Clusters explorer instead of Kubernetes panel included with OAB update
**Describe the bug**
the vscode README.md is not up to date with OAB UI changes and references the **Clusters** explorer instead of the new **Kubernetes** section.

**Expected behavior**
README should reference new UI text.

** Template in use:**
 - Python
 - https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/v1/python/python-hello-world 

**Cloud Code in use:**
 - [Cloud Code for VS Code] 
 - OS: Debian GNU/Linux rodete
 - Browser chrome
 - Version 101.0.4951.54

### PR DESCRIPTION
**Pull request by ace-n**
Fixes #1024

-------

**Note:** the change this addresses has been merged into VS Code, but **not** into Cloud Code itself - _yet_.

### CODE REVIEW

**Comment by ace-n** [comment]
@fatoboist does this address your concerns?

**Review by averikitsch — APPROVED** [review]

**Comment by sushicw** [comment]
Should this fix be applied to the other samples as well? The files are nearly identical across languages, and the Cloud Code UI is certainly consistent between them.

**Review by fatoboist — APPROVED** [review]
Looks good for now, thanks! - these changes will also affect Cloud Shell Cloud Code soon, but probably not IntelliJ Cloud Code.

**Comment by fatoboist** [comment]
> 


This change should be echoed for all Cloud Code VS Code samples.

**Comment by ace-n** [comment]
@fatoboist can you confirm this is good to merge?

_(Thanks! 😃 )_

**Review by fatoboist — APPROVED** [review]

**Pull request merged**
