### PR TITLE
Node.js: use Alpine base image

### PR DESCRIPTION
**Pull request by ace-n**

### CODE REVIEW

**Review by averikitsch — APPROVED** [review]

**Comment by iennae** [comment]
just curious how this speeds up CI for node going from slim to alpine. isn't slim the smallest form factor? or are we spending time installing git and bash so this ultimately speeds up CI? (https://hub.docker.com/_/node) It's not obvious from the PR so figure you have more insight.

**Comment by ace-n** [comment]
As discussed in our team chatroom - `alpine` images are smaller than `slim` ones, so they _should_ be faster to unpack.

Furthermore - I confirmed that an example `alpine` build outran its `slim` counterpart in [this PR](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/1096).

**Pull request merged**
