### PR TITLE
Upgrade to latest version of skaffold

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by simonz130** [comment]
1) Will it trigger installing newest skaffold for all the folks that use this in demos, etc?
2) Do we need to do it manually every time there is a new version of skaffold?
3) What happens if we don't do it and folks still update to newest skaffold? Is it all backward compatible?

**Comment by dgageot** [comment]
@simonz130 you're right that it'll require people to upgrade their skaffold if they are not using the latest one. If we don't upgrade, that's ok: skaffold will just print a warning (which we might end up removing).

The reason why I did this is that there's been a huge effort to improve the descriptions on recent schemas. But, now that I double check, `v1beta6` already has those improvements applied.

**Comment by simonz130** [comment]
Thanks David!
Let's postpone this update then for a few weeks.

**Comment by simonz130** [comment]
Closing this as we've updated to v1beta16 here: https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/155

**Pull request closed without merging**
